# Generated by Django 5.1.6 on 2025-02-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='x',
            field=models.TextField(default=''),
        ),
    ]
